// This module's own UI text. Pure data with no imports (see src/i18n/types.ts).

const en = {
  title: 'Flare',
  close: 'Close',
  intro: 'Flashes the flashlight and screen and sounds a loud whistle so people nearby can find you. Works without signal.',
  hold: 'Hold to fire the Flare',
  holding: 'Keep holding…',
  holdHint: 'Press and hold until the bar fills. A tap does nothing.',
  holdA11yHint: 'Press and hold to start the flashlight, screen strobe and whistle.',
  activeTitle: 'Flare on',
  activeTorch: 'Flashlight blinking SOS',
  activeNoTorch: 'No flashlight available. The screen and whistle are on.',
  activeSound: 'Whistle sounding at full volume',
  stop: 'Stop Flare',
  guidesHeading: 'Emergency Guides',
  guideLost: 'Lost on the trail',
  guideBleeding: 'Bleeding wounds',
  guideSnakebite: 'Snakebite',
  guideSprains: 'Sprains and fractures',
  guideHypothermia: 'Hypothermia',
  openGuideHint: 'Opens the Guide. The Flare keeps running.',
  emergencyHeading: 'Emergency number',
  emergencyNumber: '911',
  emergencyNote: 'Call once you have signal.',
  callHint: 'Opens the phone app with 911 ready to call.',
  // The Assistant's Flare tool (issue #19), shown in the Ask tab.
  toolDescription: 'Opens the Flare screen, ready to fire. It never fires the Flare: that takes a 1.5 s hold.',
  toolTitle: 'Flare',
  toolOpened: 'I opened the Flare. To signal, press and hold the red button for 1.5 seconds: the flashlight blinks SOS, the screen flashes and a loud whistle sounds. Nothing fires until you hold it.',
  toolNotOpened: 'Tap SOS at the top right to open the Flare. To signal, press and hold the red button for 1.5 seconds.',
};

const fil: Record<keyof typeof en, string> = {
  title: 'Flare',
  close: 'Isara',
  intro: 'Kumikislap ang flashlight at screen at tumutunog ang malakas na pito para mahanap ka ng mga nasa malapit. Gumagana kahit walang signal.',
  hold: 'Pindutin nang matagal para paganahin ang Flare',
  holding: 'Huwag bitawan…',
  holdHint: 'Pindutin nang matagal hanggang mapuno ang guhit. Walang mangyayari sa isang pindot lang.',
  holdA11yHint: 'Pindutin nang matagal para buksan ang flashlight, pagkislap ng screen at pito.',
  activeTitle: 'Bukas ang Flare',
  activeTorch: 'Kumikislap ng SOS ang flashlight',
  activeNoTorch: 'Walang magagamit na flashlight. Bukas ang screen at pito.',
  activeSound: 'Tumutunog ang pito nang pinakamalakas',
  stop: 'Itigil ang Flare',
  guidesHeading: 'Mga gabay pang-emergency',
  guideLost: 'Naligaw sa trail',
  guideBleeding: 'Mga sugat na dumudugo',
  guideSnakebite: 'Kagat ng ahas',
  guideSprains: 'Pilay at bali',
  guideHypothermia: 'Hypothermia (sobrang lamig ng katawan)',
  openGuideHint: 'Bubuksan ang gabay. Tuloy pa rin ang Flare.',
  emergencyHeading: 'Numerong pang-emergency',
  emergencyNumber: '911',
  emergencyNote: 'Tumawag kapag may signal na.',
  callHint: 'Bubuksan ang phone app na handa nang tawagan ang 911.',
  toolDescription: 'Binubuksan ang screen ng Flare, handa nang paganahin. Hindi nito pinapagana ang Flare: kailangan ng 1.5 segundong pagpindot.',
  toolTitle: 'Flare',
  toolOpened: 'Binuksan ko ang Flare. Para mag-signal, pindutin nang matagal ang pulang button nang 1.5 segundo: kikislap ng SOS ang flashlight, kikislap ang screen at tutunog ang malakas na pito. Walang mangyayari hangga’t hindi mo ito pinipindot nang matagal.',
  toolNotOpened: 'I-tap ang SOS sa kanang itaas para buksan ang Flare. Para mag-signal, pindutin nang matagal ang pulang button nang 1.5 segundo.',
};

export default { en, fil };
