#!/usr/bin/env python3
"""Write supabase/seed/ulap.sql from content/ulap/ and content/destinations/mt-ulap/.

    python3 -I content/ulap/scripts/build_seed.py --map-bytes <size of ulap.pmtiles>

supabase/seed/seed-ulap.sh runs this with the size of the map file it uploads, so the
Destination row always matches the file in Storage. Standard library only.

Trails and Waypoints come from content/ulap/{trail,waypoints}.geojson. Passages come from
the RAG drafts in content/destinations/mt-ulap/passages/*.md (format in content/README.md):
each file becomes an `-en` and a `-fil` row, with its sources resolved from SOURCES.md.

Bump PACK_VERSION whenever the Trails, Waypoints or passages change, so phones know their
downloaded pack is out of date. (A new map file of a different size bumps it on its own.)
"""

import argparse
import json
import re
from pathlib import Path
from urllib.parse import urlparse

CONTENT = Path(__file__).resolve().parent.parent
REPO = CONTENT.parent.parent
PASSAGES = REPO / "content" / "destinations" / "mt-ulap"
OUT = REPO / "supabase" / "seed" / "ulap.sql"

PACK_VERSION = 1
MAP_PATH = f"ulap-v{PACK_VERSION}.pmtiles"  # in the public 'maps' bucket

DESTINATION = {
    "id": "ulap",
    "name": "Mt. Ulap",
    "region": "Itogon, Benguet",
    # "About 1,846 m": sources give 1,843 to 1,856 m (docs/research/rag-sources.md, 4.1).
    "elevation_m": 1846,
    "summary_en": (
        "A pine and grass ridge in Itogon, Benguet, south of Baguio, about 1,846 m high. The Mt. Ulap "
        "Eco-Trail starts in Ampucao and passes Ambanaw-Paoay and Gungal Rock on the way to the summit "
        "(about 5 km); most hikers then continue down to Sta. Fe. Guides are required, there is no "
        "reliable water, and the trail closes in storms and fire season."
    ),
    "summary_fil": (
        "Isang tagaytay ng pine at damo sa Itogon, Benguet, sa timog ng Baguio, mga 1,846 m ang taas. "
        "Nagsisimula ang Mt. Ulap Eco-Trail sa Ampucao at dumadaan sa Ambanaw-Paoay at Gungal Rock "
        "papunta sa tuktok (mga 5 km); karamihan ay bumababa pagkatapos sa Sta. Fe. Kailangan ng guide, "
        "walang maaasahang tubig, at isinasara ang trail kapag may bagyo o sa panahon ng sunog."
    ),
}


# Each passage file's number -> one of the topics Batulao uses (content/batulao/README.md).
TOPICS = {
    1: "getting_there", 2: "getting_there", 6: "getting_there", 7: "getting_there", 10: "getting_there",
    3: "registration", 4: "registration", 5: "registration",
    9: "campsites",
    11: "water",
    8: "hazards", 12: "hazards", 13: "hazards", 14: "hazards", 15: "hazards", 16: "hazards",
}


def q(value):
    """SQL literal."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    return "'" + str(value).replace("'", "''") + "'"


def load_sources():
    """Source ID -> {id, title, publisher, url} from the table in SOURCES.md."""
    sources = {}
    for line in (PASSAGES / "SOURCES.md").read_text().splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) >= 4 and re.fullmatch(r"[A-Z]+\d+", cells[0]):
            sources[cells[0]] = {"id": cells[0], "title": cells[1], "publisher": cells[2], "url": cells[3]}
    return sources


def parse_passage(path):
    """(frontmatter dict, English text, Filipino text) from one passage file."""
    _, front, body = path.read_text().split("---", 2)
    meta, key = {}, None
    for line in front.strip().splitlines():
        if line.startswith("  - ") and key:
            meta.setdefault(key, []).append(line[4:].strip())
            continue
        key, _, value = line.partition(":")
        key, value = key.strip(), value.strip()
        if value.startswith("[") and value.endswith("]"):
            meta[key] = [v.strip() for v in value[1:-1].split(",") if v.strip()]
        elif value:
            meta[key] = value.strip('"')
    sections = re.split(r"^## (English|Filipino)\s*$", body, flags=re.M)
    text = {sections[i]: sections[i + 1].strip() for i in range(1, len(sections) - 1, 2)}
    return meta, text["English"], text["Filipino"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--map-bytes", type=int, required=True)
    args = ap.parse_args()

    trails = json.loads((CONTENT / "trail.geojson").read_text())["features"]
    waypoints = json.loads((CONTENT / "waypoints.geojson").read_text())["features"]
    summit = next(w for w in waypoints if w["properties"]["type"] == "summit")
    lon, lat = summit["geometry"]["coordinates"]
    sources = load_sources()

    d = DESTINATION
    lines = [
        "-- Mt. Ulap Destination Pack (issue #22). GENERATED by content/ulap/scripts/build_seed.py",
        "-- from content/ulap/{trail,waypoints}.geojson and content/destinations/mt-ulap/passages/.",
        "-- Do not edit by hand.",
        "--",
        "-- Applied by supabase/seed/seed-ulap.sh. Safe to run again: it replaces every Ulap row.",
        "-- Trails and Waypoints: © OpenStreetMap contributors, ODbL 1.0 (see content/ulap/README.md).",
        "-- Needs migration 20261009183000_content_extras.sql (name_fil, note, sources, as_of).",
        "",
        "begin;",
        "",
        "insert into public.destinations",
        "  (id, name, region, summary_en, summary_fil, latitude, longitude, elevation_m,",
        "   pack_version, map_path, map_bytes, is_placeholder, updated_at)",
        "values",
        f"  ({q(d['id'])}, {q(d['name'])}, {q(d['region'])},",
        f"   {q(d['summary_en'])},",
        f"   {q(d['summary_fil'])},",
        f"   {lat}, {lon}, {d['elevation_m']},",
        f"   {PACK_VERSION}, {q(MAP_PATH)}, {args.map_bytes}, false, now())",
        "on conflict (id) do update set",
        "  name = excluded.name, region = excluded.region,",
        "  summary_en = excluded.summary_en, summary_fil = excluded.summary_fil,",
        "  latitude = excluded.latitude, longitude = excluded.longitude, elevation_m = excluded.elevation_m,",
        "  -- At least PACK_VERSION, and one more whenever the map file itself changes.",
        "  pack_version = greatest(",
        "    excluded.pack_version,",
        "    public.destinations.pack_version",
        "      + (public.destinations.map_path <> excluded.map_path",
        "         or public.destinations.map_bytes <> excluded.map_bytes)::int),",
        "  map_path = excluded.map_path, map_bytes = excluded.map_bytes,",
        "  is_placeholder = excluded.is_placeholder, updated_at = now();",
        "",
        "-- Trails cascade to their Waypoints.",
        "delete from public.trails where destination_id = 'ulap';",
        "delete from public.reference_passages where destination_id = 'ulap';",
        "",
        "insert into public.trails (id, destination_id, name, name_fil, distance_m, geometry) values",
    ]
    rows = []
    for f in trails:
        p = f["properties"]
        geom = json.dumps(f["geometry"], separators=(",", ":"))
        rows.append(f"  ({q(p['id'])}, 'ulap', {q(p['name'])}, {q(p['name_fil'])}, {p['length_m']},\n   {q(geom)})")
    lines.append(",\n".join(rows) + ";")

    lines += ["", "insert into public.waypoints",
              "  (id, trail_id, type, name, name_fil, note, latitude, longitude, elevation_m, position, distance_m)",
              "values"]
    rows = []
    for f in waypoints:
        p = f["properties"]
        wlon, wlat = f["geometry"]["coordinates"]
        ele = p.get("ele_m")
        rows.append(
            f"  ({q(p['id'])}, {q(p['trail'])}, {q(p['type'])}, {q(p['name'])}, {q(p['name_fil'])},\n"
            f"   {q(p['note'])},\n"
            f"   {wlat}, {wlon}, {q(None if ele is None else int(round(ele)))}, {p['order']}, {p['distance_from_start_m']})"
        )
    lines.append(",\n".join(rows) + ";")

    lines += ["", "insert into public.reference_passages",
              "  (id, destination_id, topic, language, text, source, sources, as_of)", "values"]
    rows = []
    files = sorted((PASSAGES / "passages").glob("*.md"))
    for path in files:
        meta, en, fil = parse_passage(path)
        cited = [sources[s] for s in meta["sources"]]
        summary = ", ".join(dict.fromkeys(urlparse(s["url"]).netloc.removeprefix("www.") for s in cited))
        topic = TOPICS[int(path.stem.split("-", 1)[0])]
        base = "ulap-" + path.stem
        for lang, text in (("en", en), ("fil", fil)):
            rows.append(
                f"  ({q(f'{base}-{lang}')}, 'ulap', {q(topic)}, {q(lang)},\n"
                f"   {q(text)},\n"
                f"   {q(summary)},\n"
                f"   {q(json.dumps(cited, ensure_ascii=False))}::jsonb, {q(meta['last_checked'])})"
            )
    lines.append(",\n".join(rows) + ";")
    lines += ["", "commit;", ""]

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(REPO)}: {len(trails)} trails, {len(waypoints)} waypoints, "
          f"{len(rows)} passages ({len(files)} en/fil pairs), pack_version >= {PACK_VERSION}, "
          f"map {MAP_PATH} ({args.map_bytes} bytes)")


if __name__ == "__main__":
    main()
