#!/usr/bin/env python3
"""Write supabase/seed/batulao.sql from the files in content/batulao/.

    python3 -I content/batulao/scripts/build_seed.py --map-bytes <size of batulao.pmtiles>

supabase/seed/seed-batulao.sh runs this with the size of the map file it uploads, so the
Destination row always matches the file in Storage. Standard library only.

Bump PACK_VERSION whenever the Trails, Waypoints or passages change, so phones know their
downloaded pack is out of date. (A new map file of a different size bumps it on its own.)
"""

import argparse
import json
from pathlib import Path
from urllib.parse import urlparse

CONTENT = Path(__file__).resolve().parent.parent
REPO = CONTENT.parent.parent
OUT = REPO / "supabase" / "seed" / "batulao.sql"

PACK_VERSION = 2
MAP_PATH = f"batulao-v{PACK_VERSION}.pmtiles"  # in the public 'maps' bucket

DESTINATION = {
    "id": "batulao",
    "name": "Mt. Batulao",
    "region": "Nasugbu, Batangas",
    "summary_en": (
        "An 811 m grassland peak in Nasugbu, Batangas, popular for day hikes. Two Trails start at "
        "the same jump-off and meet at the summit: the New Trail (3.4 km, the usual way up) and the "
        "steeper Old Trail (4.2 km) past Camp 1. There is almost no shade and no reliable water, so "
        "carry at least 2 to 3 litres."
    ),
    "summary_fil": (
        "Bundok na 811 m ang taas sa Nasugbu, Batangas, na puno ng damuhan at patok sa day hike. "
        "Dalawang Trail ang nagsisimula sa iisang jump-off at nagtatagpo sa tuktok: ang New Trail "
        "(3.4 km, karaniwang inaakyat) at ang mas matarik na Old Trail (4.2 km) na dumadaan sa "
        "Camp 1. Halos walang lilim at walang maaasahang tubig, kaya magdala ng 2 hanggang 3 litro."
    ),
}


def q(value):
    """SQL literal."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    return "'" + str(value).replace("'", "''") + "'"


def source_summary(sources):
    """'transitpinas.com (2022), lakbaypinas.com (2026), openstreetmap.org (2026)'"""
    parts = []
    for s in sources:
        host = urlparse(s["url"]).netloc.removeprefix("www.")
        year = str(s.get("published", ""))[:4]
        parts.append(f"{host} ({year})" if year.isdigit() else host)
    return ", ".join(parts)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--map-bytes", type=int, required=True)
    args = ap.parse_args()

    trails = json.loads((CONTENT / "trail.geojson").read_text())["features"]
    trails.sort(key=lambda f: not f["properties"]["is_main"])  # New Trail (main) first
    waypoints = json.loads((CONTENT / "waypoints.geojson").read_text())["features"]
    passages = json.loads((CONTENT / "passages.json").read_text())
    summit = next(w for w in waypoints if w["properties"]["type"] == "summit")
    lon, lat = summit["geometry"]["coordinates"]

    d = DESTINATION
    lines = [
        "-- Mt. Batulao Destination Pack (issue #5). GENERATED by content/batulao/scripts/build_seed.py",
        "-- from content/batulao/{trail,waypoints}.geojson and passages.json. Do not edit by hand.",
        "--",
        "-- Applied by supabase/seed/seed-batulao.sh. Safe to run again: it replaces every Batulao row.",
        "-- Trails and Waypoints: © OpenStreetMap contributors, ODbL 1.0 (see content/batulao/README.md).",
        "-- Needs migration 20261009183000_content_extras.sql (name_fil, note, sources, as_of).",
        "",
        "begin;",
        "",
        "insert into public.destinations",
        "  (id, name, region, summary_en, summary_fil, latitude, longitude, elevation_m,",
        "   pack_version, map_path, map_bytes, is_placeholder, updated_at)",
        "values",
        f"  ({q(d['id'])}, {q(d['name'])}, {q(d['region'])},",
        f"   {q(d['summary_en'])},",
        f"   {q(d['summary_fil'])},",
        f"   {lat}, {lon}, {int(summit['properties']['ele_m'])},",
        f"   {PACK_VERSION}, {q(MAP_PATH)}, {args.map_bytes}, false, now())",
        "on conflict (id) do update set",
        "  name = excluded.name, region = excluded.region,",
        "  summary_en = excluded.summary_en, summary_fil = excluded.summary_fil,",
        "  latitude = excluded.latitude, longitude = excluded.longitude, elevation_m = excluded.elevation_m,",
        "  -- At least PACK_VERSION, and one more whenever the map file itself changes.",
        "  pack_version = greatest(",
        "    excluded.pack_version,",
        "    public.destinations.pack_version",
        "      + (public.destinations.map_path <> excluded.map_path",
        "         or public.destinations.map_bytes <> excluded.map_bytes)::int),",
        "  map_path = excluded.map_path, map_bytes = excluded.map_bytes,",
        "  is_placeholder = excluded.is_placeholder, updated_at = now();",
        "",
        "-- Trails cascade to their Waypoints.",
        "delete from public.trails where destination_id = 'batulao';",
        "delete from public.reference_passages where destination_id = 'batulao';",
        "",
        "insert into public.trails (id, destination_id, name, name_fil, distance_m, geometry) values",
    ]
    rows = []
    for f in trails:
        p = f["properties"]
        geom = json.dumps(f["geometry"], separators=(",", ":"))
        rows.append(f"  ({q(p['id'])}, 'batulao', {q(p['name'])}, {q(p['name_fil'])}, {p['length_m']},\n   {q(geom)})")
    lines.append(",\n".join(rows) + ";")

    lines += ["", "insert into public.waypoints",
              "  (id, trail_id, type, name, name_fil, note, latitude, longitude, elevation_m, position, distance_m)",
              "values"]
    rows = []
    for f in waypoints:
        p = f["properties"]
        wlon, wlat = f["geometry"]["coordinates"]
        ele = p.get("ele_m")
        rows.append(
            f"  ({q(p['id'])}, {q(p['trail'])}, {q(p['type'])}, {q(p['name'])}, {q(p['name_fil'])},\n"
            f"   {q(p['note'])},\n"
            f"   {wlat}, {wlon}, {q(None if ele is None else int(round(ele)))}, {p['order']}, {p['distance_from_start_m']})"
        )
    lines.append(",\n".join(rows) + ";")

    lines += ["", "insert into public.reference_passages",
              "  (id, destination_id, topic, language, text, source, sources, as_of)", "values"]
    rows = []
    for p in passages:
        rows.append(
            f"  ({q('batulao-' + p['id'])}, 'batulao', {q(p['topic'])}, {q(p['lang'])},\n"
            f"   {q(p['text'])},\n"
            f"   {q(source_summary(p['sources']))},\n"
            f"   {q(json.dumps(p['sources'], ensure_ascii=False))}::jsonb, {q(p['as_of'])})"
        )
    lines.append(",\n".join(rows) + ";")
    lines += ["", "commit;", ""]

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(REPO)}: {len(trails)} trails, {len(waypoints)} waypoints, "
          f"{len(passages)} passages, pack_version >= {PACK_VERSION}, map {MAP_PATH} ({args.map_bytes} bytes)")


if __name__ == "__main__":
    main()
