// This module's own UI text. Pure data with no imports (see src/i18n/types.ts).
// {name} placeholders are filled in with fill() from ./format.

const en = {
  loading: 'Loading Destinations…',
  offlineNote: 'You’re offline. Showing the Destinations on your phone.',
  emptyOfflineTitle: 'No Destinations on your phone',
  emptyOfflineBody: 'Connect to the internet to see Destinations and download one for the trail.',
  emptyTitle: 'No Destinations yet',
  emptyBody: 'Pull down to check again.',
  worksOffline: 'Works offline',
  back: 'All Destinations',
  regionElevation: '{region} · {elevation} m',
  placeholder: 'Sample content, not for real trail use.',
  notDownloaded: 'Download this Destination to use it on the trail without signal.',
  download: 'Download for offline use ({size})',
  update: 'Download the update ({size})',
  downloading: 'Downloading… {percent}%',
  downloadingBytes: '{done} of {total}',
  downloadFailed: 'The download failed: {error}',
  retry: 'Try again',
  downloaded: 'On your phone since {date} · {size}',
  trails: 'Trails',
  trailDistance: '{km} km',
  waypoints: 'Waypoints',
  waypointDistance: '{km} km from the jump-off',
  elevation: '{elevation} m',
  jump_off: 'Jump-off',
  campsite: 'Campsite',
  water: 'Water',
  summit: 'Summit',
  reference: 'Reference info',
  source: 'Source: {source}',
};

const fil: Record<keyof typeof en, string> = {
  loading: 'Nilo-load ang mga Destination…',
  offlineNote: 'Offline ka. Ipinapakita ang mga Destination na nasa phone mo.',
  emptyOfflineTitle: 'Walang Destination sa phone mo',
  emptyOfflineBody: 'Kumonekta sa internet para makita ang mga Destination at mag-download ng isa para sa trail.',
  emptyTitle: 'Wala pang Destination',
  emptyBody: 'Hilahin pababa para tingnan ulit.',
  worksOffline: 'Gumagana kahit offline',
  back: 'Lahat ng Destination',
  regionElevation: '{region} · {elevation} m',
  placeholder: 'Sample na nilalaman, hindi para sa totoong pag-akyat.',
  notDownloaded: 'I-download ang Destination na ito para magamit sa trail kahit walang signal.',
  download: 'I-download para sa offline ({size})',
  update: 'I-download ang update ({size})',
  downloading: 'Dina-download… {percent}%',
  downloadingBytes: '{done} sa {total}',
  downloadFailed: 'Pumalya ang pag-download: {error}',
  retry: 'Subukan ulit',
  downloaded: 'Nasa phone mo mula {date} · {size}',
  trails: 'Mga Trail',
  trailDistance: '{km} km',
  waypoints: 'Mga Waypoint',
  waypointDistance: '{km} km mula sa jump-off',
  elevation: '{elevation} m',
  jump_off: 'Jump-off',
  campsite: 'Campsite',
  water: 'Tubig',
  summit: 'Tuktok',
  reference: 'Impormasyon',
  source: 'Pinagmulan: {source}',
};

export default { en, fil };
