// The Assistant's UI text (the Ask tab). Pure data with no imports (see src/i18n/types.ts).
// {name} placeholders are filled in with fill() from ./format.

const en = {
  introTitle: 'Ask about the trail',
  introBody:
    'Ask about hiking and camping, your Destination, gear, trail food, getting to the jump-off, or using Tahak. It works offline, and every answer shows where it came from.',
  exampleWater: 'Is there water on the trail?',
  exampleFood: 'What should I eat before a climb?',
  exampleDownload: 'How do I download a Destination Pack?',
  inputPlaceholder: 'Ask the Assistant…',
  send: 'Send',
  camera: 'Ask about a photo',
  takePhoto: 'Take a photo',
  choosePhoto: 'Choose from gallery',
  cancel: 'Cancel',
  photoSheetBody: 'The photo goes with your next question. It stays on this phone.',
  cameraDenied: 'Tahak can’t use the camera. Allow it in Settings, or choose a photo from the gallery.',
  photoAttached: 'Photo attached. Ask about it, or just send.',
  removePhoto: 'Remove photo',
  yourPhoto: 'Your photo',
  photoPlaceholder: 'Ask about the photo…',
  // What the model is asked when a photo is sent with no text.
  photoDefaultQuestion: 'What is in this photo?',
  readingPhoto: 'Reading the photo… {seconds} s',
  answeringPhoto: 'Looking at the photo… {seconds} s',
  photoTiming: 'From your photo · first words after {seconds} s',
  // The model said the photo isn't about the outdoors (ADR 0005). Fixed text, model text hidden.
  photoOffTopic:
    'I can only help with photos from the trail or camp: plants, animals, terrain, sky and weather, water, gear or your campsite. For an injury or a bite, open the Guides.',
  you: 'Your question',
  assistant: "The Assistant's answer",
  // The fixed off-topic reply (ADR 0005). Shown without running the model.
  offTopic:
    'I can only help with hiking and camping, outdoor first aid, gear, weather on the trail, your Destination, food for the trail, getting to and from the jump-off, local culture, and using Tahak. Try asking about one of those.',
  answering: 'Answering…',
  loadingModel: 'Getting the Assistant ready… {percent}%',
  indexing: 'Preparing passages for search… {done} of {total}',
  answerError: 'The Assistant could not answer: {error}',
  sources: 'Sources',
  appHelp: 'App help',
  guideChip: 'Guide: {title}',
  sourceLine: 'Source: {source}',
  helpNote: 'General advice written by the Tahak team, not facts about a Destination.',
  close: 'Close',
  packsIgnored: 'Test mode: Destination Packs are ignored, so only the Guides and app help are used.',
  topicGettingThere: 'Getting there',
  topicRegistration: 'Registration and fees',
  topicWater: 'Water',
  topicCampsites: 'Campsites',
  topicHazards: 'Hazards',
};

const fil: Record<keyof typeof en, string> = {
  introTitle: 'Magtanong tungkol sa trail',
  introBody:
    'Magtanong tungkol sa hiking at camping, sa Destination mo, gamit, pagkain sa trail, pagpunta sa jump-off, o paggamit ng Tahak. Gumagana ito offline, at bawat sagot ay may nakalagay kung saan galing.',
  exampleWater: 'May tubig ba sa trail?',
  exampleFood: 'Ano ang kakainin bago umakyat?',
  exampleDownload: 'Paano mag-download ng Destination Pack?',
  inputPlaceholder: 'Magtanong sa Assistant…',
  send: 'Ipadala',
  camera: 'Magtanong tungkol sa litrato',
  takePhoto: 'Kumuha ng litrato',
  choosePhoto: 'Pumili sa gallery',
  cancel: 'Kanselahin',
  photoSheetBody: 'Kasama ang litrato sa susunod mong tanong. Sa phone na ito lang ito.',
  cameraDenied: 'Hindi magamit ng Tahak ang camera. Payagan ito sa Settings, o pumili ng litrato sa gallery.',
  photoAttached: 'May kasamang litrato. Magtanong tungkol dito, o ipadala na.',
  removePhoto: 'Alisin ang litrato',
  yourPhoto: 'Ang litrato mo',
  photoPlaceholder: 'Magtanong tungkol sa litrato…',
  photoDefaultQuestion: 'Ano ang nasa litratong ito?',
  readingPhoto: 'Binabasa ang litrato… {seconds} s',
  answeringPhoto: 'Tinitingnan ang litrato… {seconds} s',
  photoTiming: 'Mula sa litrato mo · unang salita pagkatapos ng {seconds} s',
  photoOffTopic:
    'Ang kaya ko lang sagutin ay mga litrato mula sa trail o camp: halaman, hayop, lupa, langit at panahon, tubig, gamit, o ang campsite mo. Para sa sugat o kagat, buksan ang Guides.',
  you: 'Tanong mo',
  assistant: 'Sagot ng Assistant',
  offTopic:
    'Pasensya na, ang kaya ko lang sagutin ay tungkol sa hiking at camping, first aid sa labas, gamit, panahon sa trail, ang Destination mo, pagkain sa trail, pagpunta at pag-uwi mula sa jump-off, lokal na kultura, at paggamit ng Tahak. Subukan mong magtanong tungkol sa mga iyan.',
  answering: 'Sumasagot…',
  loadingModel: 'Inihahanda ang Assistant… {percent}%',
  indexing: 'Inihahanda ang mga passage para sa paghahanap… {done} sa {total}',
  answerError: 'Hindi nakasagot ang Assistant: {error}',
  sources: 'Pinagkunan',
  appHelp: 'Tulong sa app',
  guideChip: 'Gabay: {title}',
  sourceLine: 'Pinagkunan: {source}',
  helpNote: 'Pangkalahatang payo mula sa Tahak team, hindi impormasyon tungkol sa isang Destination.',
  close: 'Isara',
  packsIgnored: 'Test mode: hindi ginagamit ang mga Destination Pack, kaya Guides at tulong sa app lang ang gamit.',
  topicGettingThere: 'Paano pumunta',
  topicRegistration: 'Registration at bayad',
  topicWater: 'Tubig',
  topicCampsites: 'Mga campsite',
  topicHazards: 'Mga panganib',
};

export default { en, fil };
