// Expo app config. A .js file rather than app.json so it can carry comments.
//
// PAGE_DAY mirrors the day `page` token in src/theme/tokens.ts; test/app-config.test.ts
// fails if they drift apart.
const PAGE_DAY = '#F7F4EC';

// userInterfaceStyle is pinned to 'light'. Tahak draws its own day and night themes from an
// in-app toggle (later: sunrise and sunset), so native surfaces such as the launch screen and
// system dialogs must not switch on their own with the phone's dark mode and disagree with it.
// 'light' matches the default day theme; the cost is a light launch screen before a night start.
module.exports = {
  expo: {
    name: 'Tahak',
    slug: 'tahak',
    scheme: 'tahak',
    version: '0.1.0',
    orientation: 'portrait',
    icon: './assets/icon.png',
    userInterfaceStyle: 'light',
    backgroundColor: PAGE_DAY,
    ios: {
      supportsTablet: false,
    },
    android: {
      package: 'com.tahak.app',
      adaptiveIcon: {
        backgroundColor: PAGE_DAY,
        foregroundImage: './assets/android-icon-foreground.png',
        backgroundImage: './assets/android-icon-background.png',
        monochromeImage: './assets/android-icon-monochrome.png',
      },
      predictiveBackGestureEnabled: false,
    },
    plugins: [
      'expo-dev-client',
      [
        'expo-font',
        {
          fonts: [
            './node_modules/@expo-google-fonts/barlow/400Regular/Barlow_400Regular.ttf',
            './node_modules/@expo-google-fonts/barlow/500Medium/Barlow_500Medium.ttf',
            './node_modules/@expo-google-fonts/barlow/600SemiBold/Barlow_600SemiBold.ttf',
            './node_modules/@expo-google-fonts/barlow-condensed/600SemiBold/BarlowCondensed_600SemiBold.ttf',
            './node_modules/@expo-google-fonts/barlow-condensed/700Bold/BarlowCondensed_700Bold.ttf',
            './node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/MaterialCommunityIcons.ttf',
          ],
        },
      ],
      'expo-system-ui',
      [
        'expo-image-picker',
        {
          // The Assistant spike's "Take photo". No photo library access is needed.
          cameraPermission: 'Tahak uses the camera so you can ask the Assistant about a photo.',
          photosPermission: false,
          microphonePermission: false,
        },
      ],
      // On-device model runtime. Adds the optional OpenCL (Adreno GPU) and Hexagon (NPU)
      // native libraries to the manifest so llama.rn can load them when the phone has them.
      ['llama.rn', { enableOpenCLAndHexagon: true }],
      // The Hike map (issue #6). MapLibre Native renders the Destination Pack's PMTiles file;
      // withMapAssets bundles the glyphs and sprites the style needs, so nothing is fetched.
      '@maplibre/maplibre-react-native',
      './plugins/withMapAssets',
      [
        'expo-location',
        {
          // Foreground only: the GPS dot on the Hike map. Android shows its own system dialog;
          // the app explains why first, in the hiker's language.
          locationWhenInUsePermission: 'Tahak uses your location to show where you are on the trail map.',
          isAndroidBackgroundLocationEnabled: false,
          isIosBackgroundLocationEnabled: false,
        },
      ],
      [
        'expo-notifications',
        {
          // Deviation alerts (issue #8). The alert tone, generated by
          // scripts/build-deviation-sound.py, goes into res/raw for the notification channel;
          // the small icon is the monochrome app icon (Android uses only its shape).
          icon: './assets/android-icon-monochrome.png',
          sounds: ['./assets/sounds/deviation_alert.wav'],
        },
      ],
      './plugins/withArm64Only',
      './plugins/withLlamaRnVariants',
    ],
  },
};
