// This module's own UI text. Pure data with no imports (see src/i18n/types.ts).
// {name} placeholders are filled in with fill() from ./format.

const en = {
  title: 'Forecast',
  // How old the saved Forecast is.
  asOf: 'As of {age}',
  ageJustNow: 'just now',
  ageMinute: '1 minute ago',
  ageMinutes: '{count} minutes ago',
  ageHour: '1 hour ago',
  ageHours: '{count} hours ago',
  ageDay: '1 day ago',
  ageDays: '{count} days ago',
  refreshing: 'Updating…',
  refreshFailed: 'Couldn’t update. It updates by itself once you’re back online.',
  refresh: 'Update now',
  none: 'No Forecast saved yet. It’s saved by itself the next time you’re online.',
  loading: 'Reading the saved Forecast…',
  expired: 'The saved Forecast has run out of days. It updates by itself once you’re back online.',
  lessReliable: 'Less reliable from here on: forecasts this far ahead often change.',
  lessReliableTag: 'Less reliable',
  // Day labels.
  today: 'Today',
  tomorrow: 'Tomorrow',
  day0: 'Sun',
  day1: 'Mon',
  day2: 'Tue',
  day3: 'Wed',
  day4: 'Thu',
  day5: 'Fri',
  day6: 'Sat',
  temps: '{max}° / {min}°',
  rain: '{mm} mm rain',
  rainChance: '{chance}% rain',
  // Conditions.
  clear: 'Clear',
  partlyCloudy: 'Partly cloudy',
  cloudy: 'Cloudy',
  fog: 'Fog',
  drizzle: 'Drizzle',
  rainy: 'Rain',
  showers: 'Rain showers',
  snow: 'Snow',
  thunderstorm: 'Thunderstorms',
  // Warnings (butter, never red: ADR 0004).
  warnThunderstorm: 'Thunderstorms',
  warnHeavyRain: 'Heavy rain',
  warnStrongWind: 'Strong wind',
  warnHeat: 'Extreme heat',
  warningLabel: 'Weather warning: {warnings}',
  // The Hike panel's chip.
  chipNone: 'No Forecast saved',
  chipExpired: 'Saved Forecast is out of date',
};

const fil: Record<keyof typeof en, string> = {
  title: 'Taya ng panahon',
  asOf: 'Kuha {age}',
  ageJustNow: 'ngayon lang',
  ageMinute: '1 minuto na ang nakalipas',
  ageMinutes: '{count} minuto na ang nakalipas',
  ageHour: '1 oras na ang nakalipas',
  ageHours: '{count} oras na ang nakalipas',
  ageDay: '1 araw na ang nakalipas',
  ageDays: '{count} araw na ang nakalipas',
  refreshing: 'Ina-update…',
  refreshFailed: 'Hindi ma-update. Mag-a-update ito nang kusa pagbalik ng signal.',
  refresh: 'I-update ngayon',
  none: 'Wala pang naka-save na taya ng panahon. Kusa itong mase-save sa susunod na may internet ka.',
  loading: 'Binabasa ang naka-save na taya ng panahon…',
  expired: 'Lipas na ang lahat ng araw sa naka-save na taya. Mag-a-update ito nang kusa pagbalik ng signal.',
  lessReliable: 'Hindi na gaanong maaasahan mula rito: madalas magbago ang taya sa malalayong araw.',
  lessReliableTag: 'Hindi gaanong maaasahan',
  today: 'Ngayon',
  tomorrow: 'Bukas',
  day0: 'Lin',
  day1: 'Lun',
  day2: 'Mar',
  day3: 'Miy',
  day4: 'Huw',
  day5: 'Biy',
  day6: 'Sab',
  temps: '{max}° / {min}°',
  rain: '{mm} mm na ulan',
  rainChance: '{chance}% tsansa ng ulan',
  clear: 'Maaliwalas',
  partlyCloudy: 'Bahagyang maulap',
  cloudy: 'Maulap',
  fog: 'Mahamog',
  drizzle: 'Ambon',
  rainy: 'Ulan',
  showers: 'Pabugso-bugsong ulan',
  snow: 'Niyebe',
  thunderstorm: 'Kulog at kidlat',
  warnThunderstorm: 'Kulog at kidlat',
  warnHeavyRain: 'Malakas na ulan',
  warnStrongWind: 'Malakas na hangin',
  warnHeat: 'Matinding init',
  warningLabel: 'Babala sa panahon: {warnings}',
  chipNone: 'Walang naka-save na taya',
  chipExpired: 'Luma na ang naka-save na taya',
};

export default { en, fil };
