// This module's own UI text. Pure data with no imports (see src/i18n/types.ts).

const en = {
  loading: 'Opening the map…',
  emptyTitle: 'No map on your phone yet',
  emptyBody: 'Download a Destination in Explore. Its map then works here on the trail, even without signal.',
  mapLabel: 'Trail map',
  recenter: 'Center the map on my position',
  noFix: 'No GPS position yet. Stay where you can see the sky, then try again.',
  servicesOff: 'Location is turned off on your phone. Turn it on to see where you are. GPS works without signal.',
  locationAsk: 'Allow location to see where you are on the map. GPS works without signal.',
  allowLocation: 'Allow location',
  locationBlocked: 'Location is off for Tahak. Turn it on in the phone’s settings to see where you are.',
  openSettings: 'Open settings',
  // The Trail picker, before a Hike (issue #7).
  pickTrail: 'Choose a Trail',
  trailDistance: '{km} km',
  noTrails: 'This Destination has no Trails yet, so a Hike can’t start.',
  startHike: 'Start Hike',
  simulatedWalk: 'Simulated walk',
  simulatedWalkHint: 'Demo: walks the Trail and back by itself, without GPS.',
  // During a Hike.
  hikeOn: 'Hike on {trail}',
  waitingForPosition: 'Waiting for your GPS position… Stay where you can see the sky.',
  nextWaypoint: 'Next Waypoint · {type}',
  jump_off: 'Jump-off',
  campsite: 'Campsite',
  water: 'Water',
  summit: 'Summit',
  etaUnderMinute: 'under 1 min',
  etaMinutes: 'about {minutes} min',
  etaHours: 'about {hours} h {minutes} min',
  distanceEta: '{distance} · {eta}',
  progressUp: 'Up the Trail · {percent}%',
  progressDown: 'Back to the jump-off · {percent}%',
  progressLabel: 'Progress along the Trail',
  atTop: 'You’ve reached the end of the Trail. Head back when you’re ready.',
  atJumpOff: 'You’re back at the jump-off.',
  endHike: 'End Hike',
  endConfirmTitle: 'End this Hike?',
  endConfirmBody: 'Tracking stops, and you can pick a Trail for a new Hike.',
  keepHiking: 'Keep hiking',
  endSuggestion: 'You’re back near the jump-off. End the Hike?',
  // The simulated walk, while it runs.
  simulationRunning: 'Simulated walk · {speed}×',
  simulationNote: 'Not your real position.',
  // The button shows the speed it switches to, not the current one (the title says that).
  simulationSpeed: 'Switch to {speed}×',
  simulationSpeedHint: 'Change how fast the simulated walk goes',
  goOffTrail: 'Go off the Trail',
  scriptedOffTrail: 'Scripted: {metres} m off the Trail',
  // Required wherever the map appears (OpenStreetMap and Protomaps licences).
  attribution: '© OpenStreetMap contributors · © Protomaps',
};

const fil: Record<keyof typeof en, string> = {
  loading: 'Binubuksan ang mapa…',
  emptyTitle: 'Wala pang mapa sa phone mo',
  emptyBody: 'Mag-download ng Destination sa Tuklasin. Gagana rito ang mapa nito sa trail, kahit walang signal.',
  mapLabel: 'Mapa ng trail',
  recenter: 'Igitna ang mapa sa kinaroroonan ko',
  noFix: 'Wala pang GPS na posisyon. Pumunta kung saan kita ang langit, saka subukan ulit.',
  servicesOff: 'Naka-off ang lokasyon sa phone mo. I-on ito para makita kung nasaan ka. Gumagana ang GPS kahit walang signal.',
  locationAsk: 'Payagan ang lokasyon para makita kung nasaan ka sa mapa. Gumagana ang GPS kahit walang signal.',
  allowLocation: 'Payagan ang lokasyon',
  locationBlocked: 'Naka-off ang lokasyon para sa Tahak. I-on ito sa settings ng phone para makita kung nasaan ka.',
  openSettings: 'Buksan ang settings',
  pickTrail: 'Pumili ng Trail',
  trailDistance: '{km} km',
  noTrails: 'Wala pang Trail ang Destination na ito, kaya hindi pa makakapagsimula ng Hike.',
  startHike: 'Simulan ang Hike',
  simulatedWalk: 'Kunwaring lakad',
  simulatedWalkHint: 'Demo: kusang nilalakad ang Trail paakyat at pabalik, walang GPS.',
  hikeOn: 'Hike sa {trail}',
  waitingForPosition: 'Hinihintay ang GPS na posisyon mo… Pumunta kung saan kita ang langit.',
  nextWaypoint: 'Susunod na Waypoint · {type}',
  jump_off: 'Jump-off',
  campsite: 'Campsite',
  water: 'Tubig',
  summit: 'Tuktok',
  etaUnderMinute: 'wala pang 1 minuto',
  etaMinutes: 'mga {minutes} minuto',
  etaHours: 'mga {hours} oras {minutes} minuto',
  distanceEta: '{distance} · {eta}',
  progressUp: 'Paakyat · {percent}%',
  progressDown: 'Pabalik sa jump-off · {percent}%',
  progressLabel: 'Pag-usad sa Trail',
  atTop: 'Narating mo na ang dulo ng Trail. Bumalik kapag handa ka na.',
  atJumpOff: 'Nakabalik ka na sa jump-off.',
  endHike: 'Tapusin ang Hike',
  endConfirmTitle: 'Tapusin ang Hike na ito?',
  endConfirmBody: 'Titigil ang pagsubaybay, at puwede kang pumili ng Trail para sa bagong Hike.',
  keepHiking: 'Ituloy ang Hike',
  endSuggestion: 'Malapit ka na ulit sa jump-off. Tapusin na ang Hike?',
  simulationRunning: 'Kunwaring lakad · {speed}×',
  simulationNote: 'Hindi ito ang totoong kinaroroonan mo.',
  simulationSpeed: 'Gawing {speed}×',
  simulationSpeedHint: 'Palitan ang bilis ng kunwaring lakad',
  goOffTrail: 'Lumihis sa Trail',
  scriptedOffTrail: 'Naka-script: {metres} m palayo sa Trail',
  // The attribution is a licence notice and stays as written.
  attribution: '© OpenStreetMap contributors · © Protomaps',
};

export default { en, fil };
